### DESCRIPTION ###
### This program allows the user to enter a number 0 - 99 and it will return the 7-segment display of that number using the turtle module

import turtle as trtl
import time

lighter = trtl.Turtle()
lighter.speed(0)
lighter.ht()
wn = trtl.Screen()
resetFalse = False

def tensOne():
  lighter.penup()             # Fills in top left (# 1) of tens place
  lighter.goto(-150, 100)
  lighter.begin_fill()
  lighter.setheading(-90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def tensTwo():
  lighter.penup()             # Fills in top (# 2) of tens place
  lighter.goto(-150, 130)
  lighter.begin_fill()
  lighter.setheading(0)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def tensThree():
  lighter.penup()             # Fills in top right (# 3) of tens place
  lighter.goto(-50, 0)
  lighter.begin_fill()
  lighter.setheading(90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def tensFive():
  lighter.penup()             # Fills in center (# 5) of tens place
  lighter.goto(-150, 0)
  lighter.begin_fill()
  lighter.setheading(0)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def tensSeven():
  lighter.penup()             # Fills in bottom left (# 7) of tens place
  lighter.goto(-150, -30)
  lighter.begin_fill()
  lighter.setheading(-90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def tensEight():
  lighter.penup()             # Fills in bottom (# 8) of tens place
  lighter.goto(-150, -130)
  lighter.begin_fill()
  lighter.setheading(0)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def tensNine():
  lighter.penup()             # Fills in bottom right (# 9) of tens place
  lighter.goto(-50, -130)
  lighter.begin_fill()
  lighter.setheading(90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesOne():
  lighter.penup()             # Fills in top left (# 1) of ones place
  lighter.goto(50, 100)
  lighter.begin_fill()
  lighter.setheading(-90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesTwo():
  lighter.penup()             # Fills in top (# 2) of ones place
  lighter.goto(50, 130)
  lighter.begin_fill()
  lighter.setheading(0)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesThree():
  lighter.penup()             # Fills in top right (# 3) of ones place
  lighter.goto(150, 0)
  lighter.begin_fill()
  lighter.setheading(90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesFive():
  lighter.penup()             # Fills in center (# 5) of ones place
  lighter.goto(50, 0)
  lighter.begin_fill()
  lighter.setheading(0)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesSeven():
  lighter.penup()             # Fills in bottom left (# 7) of ones place
  lighter.goto(50, -30)
  lighter.begin_fill()
  lighter.setheading(-90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesEight():
  lighter.penup()             # Fills in bottom (# 8) of ones place
  lighter.goto(50, -130)
  lighter.begin_fill()
  lighter.setheading(0)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def onesNine():
  lighter.penup()             # Fills in bottom right (# 9) of ones place
  lighter.goto(150, -130)
  lighter.begin_fill()
  lighter.setheading(90)
  for light in range(2):
    lighter.forward(100)
    lighter.right(90)
    lighter.forward(30)
    lighter.right(90)
  lighter.end_fill()
def reset():
  lighter.penup()
  lighter.ht()
  lighter.speed(0)
  lighter.goto(-100,0)
  lighter.pendown()
  lighter.forward(80)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(160)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(80)
  lighter.penup()
  lighter.forward(-50)
  lighter.left(90)
  lighter.pendown()
  
  lighter.forward(130)
  lighter.right(90)
  lighter.forward(100)
  lighter.right(90)
  lighter.forward(160)
  lighter.right(90)
  lighter.forward(100)
  lighter.right(90)
  lighter.forward(30)
  lighter.right(180)
  lighter.penup()
  
  lighter.forward(30)
  lighter.right(90)
  lighter.pendown()
  lighter.forward(30)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(160)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(30)
  lighter.left(90)
  lighter.forward(130)
  lighter.right(90)
  lighter.forward(100)
  lighter.right(90)
  lighter.forward(130)
  
  # Ones Place Counter
  lighter.setheading(0)
  lighter.penup()
  lighter.goto(100,0)
  lighter.pendown()
  lighter.forward(80)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(160)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(80)
  lighter.penup()
  lighter.forward(-50)
  lighter.left(90)
  lighter.pendown()
  
  lighter.forward(130)
  lighter.right(90)
  lighter.forward(100)
  lighter.right(90)
  lighter.forward(160)
  lighter.right(90)
  lighter.forward(100)
  lighter.right(90)
  lighter.forward(30)
  lighter.right(180)
  lighter.penup()
  
  lighter.forward(30)
  lighter.right(90)
  lighter.pendown()
  lighter.forward(30)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(160)
  lighter.left(90)
  lighter.forward(100)
  lighter.left(90)
  lighter.forward(30)
  lighter.left(90)
  lighter.forward(130)
  lighter.right(90)
  lighter.forward(100)
  lighter.right(90)
  lighter.forward(130)

reset()
while (resetFalse == False):
  while True:
    userNum = int(input("Enter a number (0 - 99)"))
    
    if (userNum == -1):                             ### ENTERS SECRET BRUTE FORCE MENU
      print("")
      print("*** ENTERING BRUTE FORCE MENU- ***")
      print("")
      userNum = 0
      bruteForce = True
      break                                   # (skips to line 289)
    
    if (userNum >= 100 or userNum < 0):  # User number must be between 0 - 99
      print("Please pick a number 0-99")
      continue
    else:
      bruteForce = False
      break                                   # (skips to line 946 - 1595)
  
  # Enters brute force command only if userNum == -1 and bruteForce == True
  while (userNum > -1 and userNum < 99 and bruteForce == True):
    if (userNum < 10):
      tensOne()
      tensTwo()
      tensThree()
      tensSeven()
      tensEight()
      tensNine()
    
      if (userNum == 1):
        onesThree()
        onesNine()
      elif (userNum == 2):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 3):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 4):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 5):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 6):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 7):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 8):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 9):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 20):
      tensThree()
      tensNine()
      if (userNum == 11):
        onesThree()
        onesNine()
      elif (userNum == 12):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 13):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 14):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 15):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 16):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 17):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 18):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 19):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 30):
      tensTwo()
      tensThree()
      tensFive()
      tensSeven()
      tensEight()
      if (userNum == 21):
        onesThree()
        onesNine()
      elif (userNum == 22):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 23):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 24):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 25):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 26):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 27):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 28):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 29):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 40):
      tensTwo()
      tensThree()
      tensFive()
      tensNine()
      tensEight()
      if (userNum == 31):
        onesThree()
        onesNine()
      elif (userNum == 32):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 33):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 34):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 35):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 36):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 37):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 38):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 39):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 50):
      tensOne()
      tensFive()
      tensThree()
      tensNine()
      if (userNum == 41):
        onesThree()
        onesNine()
      elif (userNum == 42):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 43):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 44):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 45):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 46):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 47):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 48):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 49):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 60):
      tensTwo()
      tensOne()
      tensFive()
      tensNine()
      tensEight()
      if (userNum == 51):
        onesThree()
        onesNine()
      elif (userNum == 52):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 53):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 54):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 55):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 56):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 57):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 58):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 59):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 70):
      tensTwo()
      tensOne()
      tensFive()
      tensNine()
      tensEight()
      tensSeven()
      if (userNum == 61):
        onesThree()
        onesNine()
      elif (userNum == 62):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 63):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 64):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 65):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 66):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 67):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 68):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 69):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 80):
      tensTwo()
      tensThree()
      tensNine()
      if (userNum == 71):
        onesThree()
        onesNine()
      elif (userNum == 72):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 73):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 74):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 75):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 76):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 77):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 78):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 79):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    elif (userNum < 90):
      tensTwo()
      tensOne()
      tensFive()
      tensNine()
      tensEight()
      tensSeven()
      tensThree()  
      if (userNum == 81):
        onesThree()
        onesNine()
      elif (userNum == 82):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 83):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 84):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 85):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 86):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 87):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 88):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 89):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    else:
      tensOne()
      tensTwo()
      tensThree()
      tensFive()
      tensNine()
      tensEight()  
      if (userNum == 91):
        onesThree()
        onesNine()
      elif (userNum == 92):
        onesTwo()
        onesThree()
        onesFive()
        onesSeven()
        onesEight()
      elif (userNum == 93):
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 94):
        onesOne()
        onesFive()
        onesThree()
        onesNine()
      elif (userNum == 95):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
      elif (userNum == 96):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
      elif (userNum == 97):
        onesTwo()
        onesThree()
        onesNine()
      elif (userNum == 98):
        onesTwo()
        onesOne()
        onesFive()
        onesNine()
        onesEight()
        onesSeven()
        onesThree()
      elif (userNum == 99):
        onesOne()
        onesTwo()
        onesThree()
        onesFive()
        onesNine()
        onesEight()
      else:
        onesOne()
        onesTwo()
        onesThree()
        onesSeven()
        onesEight()
        onesNine()
    userNum += 1
    print(userNum)
    time.sleep(0.5)
    lighter.reset()      # Resets the function, if userNum == 99+,
    reset()              # escapes while loop, skips to line 1595
  
  # If not in brute force, enters one number normally
  if (userNum < 10):
    tensOne()
    tensTwo()
    tensThree()
    tensSeven()
    tensEight()
    tensNine()
    
    if (userNum == 1):
      onesThree()
      onesNine()
    elif (userNum == 2):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 3):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 4):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 5):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 6):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 7):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 8):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 9):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine()  # 0 - 10
  elif (userNum < 20):
    tensThree()
    tensNine()
    if (userNum == 11):
      onesThree()
      onesNine()
    elif (userNum == 12):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 13):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 14):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 15):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 16):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 17):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 18):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 19):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 11 - 20
  elif (userNum < 30):
    tensTwo()
    tensThree()
    tensFive()
    tensSeven()
    tensEight()
    if (userNum == 21):
      onesThree()
      onesNine()
    elif (userNum == 22):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 23):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 24):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 25):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 26):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 27):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 28):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 29):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 21 - 30
  elif (userNum < 40):
    tensTwo()
    tensThree()
    tensFive()
    tensNine()
    tensEight()
    if (userNum == 31):
      onesThree()
      onesNine()
    elif (userNum == 32):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 33):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 34):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 35):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 36):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 37):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 38):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 39):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 31 - 40
  elif (userNum < 50):
    tensOne()
    tensFive()
    tensThree()
    tensNine()
    if (userNum == 41):
      onesThree()
      onesNine()
    elif (userNum == 42):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 43):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 44):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 45):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 46):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 47):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 48):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 49):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 41 - 50
  elif (userNum < 60):
    tensTwo()
    tensOne()
    tensFive()
    tensNine()
    tensEight()
    if (userNum == 51):
      onesThree()
      onesNine()
    elif (userNum == 52):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 53):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 54):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 55):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 56):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 57):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 58):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 59):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 51 - 60
  elif (userNum < 70):
    tensTwo()
    tensOne()
    tensFive()
    tensNine()
    tensEight()
    tensSeven()
    if (userNum == 61):
      onesThree()
      onesNine()
    elif (userNum == 62):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 63):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 64):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 65):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 66):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 67):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 68):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 69):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 61 - 70
  elif (userNum < 80):
    tensTwo()
    tensThree()
    tensNine()
    if (userNum == 71):
      onesThree()
      onesNine()
    elif (userNum == 72):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 73):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 74):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 75):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 76):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 77):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 78):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 79):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 71 - 80
  elif (userNum < 90):
    tensTwo()
    tensOne()
    tensFive()
    tensNine()
    tensEight()
    tensSeven()
    tensThree()  
    if (userNum == 81):
      onesThree()
      onesNine()
    elif (userNum == 82):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 83):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 84):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 85):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 86):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 87):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 88):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 89):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine() # 81 - 90
  else:
    tensOne()
    tensTwo()
    tensThree()
    tensFive()
    tensNine()
    tensEight()  
    if (userNum == 91):
      onesThree()
      onesNine()
    elif (userNum == 92):
      onesTwo()
      onesThree()
      onesFive()
      onesSeven()
      onesEight()
    elif (userNum == 93):
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 94):
      onesOne()
      onesFive()
      onesThree()
      onesNine()
    elif (userNum == 95):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
    elif (userNum == 96):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
    elif (userNum == 97):
      onesTwo()
      onesThree()
      onesNine()
    elif (userNum == 98):
      onesTwo()
      onesOne()
      onesFive()
      onesNine()
      onesEight()
      onesSeven()
      onesThree()
    elif (userNum == 99):
      onesOne()
      onesTwo()
      onesThree()
      onesFive()
      onesNine()
      onesEight()
    else:
      onesOne()
      onesTwo()
      onesThree()
      onesSeven()
      onesEight()
      onesNine()
  
  print("")  
  resetFalse = input("Would you like to reset? Y or N: ")   # Asks user if they 
                                                            # want to reset
  if (resetFalse == "Y"):
    resetFalse = False
    lighter.reset()
    reset()
  elif (resetFalse == "N"):
    resetFalse = True
  else:
    resetFalse = False
    lighter.reset()
    reset()

print("")
print("Goodbye")
